# Generated by Django 5.2.5 on 2025-09-03 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metricType', models.CharField(choices=[('60', '60 Yard Dash (seconds)'), ('fbvelo', 'Fastball Velocity (mph)'), ('exitvelo', 'Exit Velocity (mph)'), ('ofvelo', 'Outfield Velocity (mph)'), ('ifvelo', 'Infield Velocity (mph)')], max_length=20, verbose_name='Metric Type')),
                ('metric', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Metric')),
                ('ageCaptured', models.IntegerField(choices=[(12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(20)], verbose_name='Age Captured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Player Metric',
                'verbose_name_plural': 'Player Metrics',
            },
        ),
        migrations.CreateModel(
            name='MetricsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height (inches)')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight (lbs)')),
                ('ifVelo', models.IntegerField(blank=True, null=True, verbose_name='Infield Velocity (mph)')),
                ('ofVelo', models.IntegerField(blank=True, null=True, verbose_name='Outfield Velocity (mph)')),
                ('cVelo', models.IntegerField(blank=True, null=True, verbose_name='Catcher Velocity (mph)')),
                ('exitVelo', models.IntegerField(blank=True, null=True, verbose_name='Exit Velocity (mph)')),
                ('maxFB', models.IntegerField(blank=True, null=True, verbose_name='Max Fastball Velocity (mph)')),
                ('popTime', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Pop Time (seconds)')),
                ('sixtyyard', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='60 Yard Dash (seconds)')),
                ('changeUp', models.IntegerField(blank=True, null=True, verbose_name='Changeup Velocity (mph)')),
                ('curve', models.IntegerField(blank=True, null=True, verbose_name='Curveball Velocity (mph)')),
                ('slider', models.IntegerField(blank=True, null=True, verbose_name='Slider Velocity (mph)')),
                ('event_id', models.IntegerField(verbose_name='Event ID')),
                ('player_id', models.IntegerField(verbose_name='Player ID')),
                ('gradYear', models.IntegerField(blank=True, null=True, verbose_name='Graduation Year')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('playerage', models.IntegerField(default=0, verbose_name='Player Age')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metrics History',
                'verbose_name_plural': 'Metrics History',
                'ordering': ['-event_date', 'player_id'],
                'indexes': [models.Index(fields=['player_id'], name='main_metric_player__61e3a4_idx'), models.Index(fields=['event_date'], name='main_metric_event_d_9b393f_idx'), models.Index(fields=['event_id'], name='main_metric_event_i_d9a537_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricsRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metricType', models.CharField(choices=[('60', '60 Yard Dash (seconds)'), ('fbvelo', 'Fastball Velocity (mph)'), ('exitvelo', 'Exit Velocity (mph)'), ('ofvelo', 'Outfield Velocity (mph)'), ('ifvelo', 'Infield Velocity (mph)')], max_length=20, verbose_name='Metric Type')),
                ('Min', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Minimum Value')),
                ('Max', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Maximum Value')),
                ('Avg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Average Value')),
                ('playerAge', models.IntegerField(default=0, verbose_name='Player Age')),
            ],
            options={
                'verbose_name': 'Metrics Range',
                'verbose_name_plural': 'Metrics Ranges',
                'unique_together': {('metricType', 'playerAge')},
            },
        ),
    ]
