# Generated by Django 5.2.5 on 2026-01-03 22:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height (inches)')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight (lbs)')),
                ('ifVelo', models.IntegerField(blank=True, null=True, verbose_name='Infield Velocity (mph)')),
                ('ofVelo', models.IntegerField(blank=True, null=True, verbose_name='Outfield Velocity (mph)')),
                ('cVelo', models.IntegerField(blank=True, null=True, verbose_name='Catcher Velocity (mph)')),
                ('exitVelo', models.IntegerField(blank=True, null=True, verbose_name='Exit Velocity (mph)')),
                ('maxFB', models.IntegerField(blank=True, null=True, verbose_name='Max Fastball Velocity (mph)')),
                ('popTime', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Pop Time (seconds)')),
                ('sixtyyard', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='60 Yard Dash (seconds)')),
                ('changeUp', models.IntegerField(blank=True, null=True, verbose_name='Changeup Velocity (mph)')),
                ('curve', models.IntegerField(blank=True, null=True, verbose_name='Curveball Velocity (mph)')),
                ('slider', models.IntegerField(blank=True, null=True, verbose_name='Slider Velocity (mph)')),
                ('event_id', models.IntegerField(verbose_name='Event ID')),
                ('player_id', models.IntegerField(verbose_name='Player ID')),
                ('gradYear', models.IntegerField(blank=True, null=True, verbose_name='Graduation Year')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('playerage', models.IntegerField(default=0, verbose_name='Player Age')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metrics History',
                'verbose_name_plural': 'Metrics History',
                'ordering': ['-event_date', 'player_id'],
                'indexes': [models.Index(fields=['player_id'], name='main_metric_player__61e3a4_idx'), models.Index(fields=['event_date'], name='main_metric_event_d_9b393f_idx'), models.Index(fields=['event_id'], name='main_metric_event_i_d9a537_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricsRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metricType', models.CharField(choices=[('60', '60 Yard Dash (seconds)'), ('fbvelo', 'Fastball Velocity (mph)'), ('exitvelo', 'Exit Velocity (mph)'), ('ofvelo', 'Outfield Velocity (mph)'), ('ifvelo', 'Infield Velocity (mph)')], max_length=20, verbose_name='Metric Type')),
                ('Min', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Minimum Value')),
                ('Max', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Maximum Value')),
                ('Avg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Average Value')),
                ('playerAge', models.IntegerField(default=0, verbose_name='Player Age')),
            ],
            options={
                'verbose_name': 'Metrics Range',
                'verbose_name_plural': 'Metrics Ranges',
                'unique_together': {('metricType', 'playerAge')},
            },
        ),
        migrations.CreateModel(
            name='PlayerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metricType', models.CharField(choices=[('60', '60 Yard Dash (seconds)'), ('fbvelo', 'Fastball Velocity (mph)'), ('exitvelo', 'Exit Velocity (mph)'), ('ofvelo', 'Outfield Velocity (mph)'), ('ifvelo', 'Infield Velocity (mph)')], max_length=20, verbose_name='Metric Type')),
                ('metric', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Metric')),
                ('ageCaptured', models.IntegerField(choices=[(12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=18, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(20)], verbose_name='Age Captured')),
                ('gradClass', models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031')], default=2026, validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(2032)], verbose_name='Graduation Class')),
                ('dateCaptured', models.DateField(blank=True, null=True, verbose_name='Date Captured')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('capturedBy', models.CharField(blank=True, choices=[('perfect_game', 'Perfect Game'), ('player_metrix', 'Player Metrix'), ('self_captured', 'Self Captured')], max_length=20, null=True, verbose_name='Captured By')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Player Metric',
                'verbose_name_plural': 'Player Metrics',
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.CharField(blank=True, help_text='Comma-separated list of positions', max_length=200, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('height_inches', models.IntegerField(blank=True, null=True)),
                ('weight_lbs', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=150, null=True)),
                ('throws', models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left'), ('S', 'Switch')], max_length=1, null=True)),
                ('hits', models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left'), ('S', 'Switch')], max_length=1, null=True)),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia')], max_length=2, null=True)),
                ('picture', models.ImageField(blank=True, default='player_pics/default.jpg', null=True, upload_to='player_pics/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
