# Generated by Django 5.2.5 on 2025-09-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermetric',
            name='dateCaptured',
            field=models.DateField(blank=True, null=True, verbose_name='Date Captured'),
        ),
        migrations.AddField(
            model_name='playermetric',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Notes'),
        ),
    ]
