# Generated by Django 5.2.5 on 2025-09-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_playermetric_datecaptured_playermetric_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermetric',
            name='username',
            field=models.CharField(default='loggedout', max_length=150, verbose_name='Username'),
        ),
    ]
