# Generated by Django 5.2.5 on 2026-01-24 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_agecaptured_to_playerage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermetric',
            name='capturedBy',
            field=models.CharField(blank=True, choices=[('Perfect Game', 'Perfect Game'), ('Player Metrix', 'Player Metrix'), ('Self Captured', 'Self Captured')], max_length=20, null=True, verbose_name='Captured By'),
        ),
        migrations.AlterField(
            model_name='playermetric',
            name='playerAge',
            field=models.IntegerField(choices=[(12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(20)], verbose_name='Player Age'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='picture',
            field=models.ImageField(blank=True, default='media/player_pics/default.jpg', null=True, upload_to='media/player_pics/'),
        ),
    ]
