# Generated by Django 5.2.5 on 2025-11-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_playerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermetric',
            name='capturedBy',
            field=models.CharField(blank=True, choices=[('perfect_game', 'Perfect Game'), ('player_metrix', 'Player Metrix'), ('self_captured', 'Self Captured')], max_length=20, null=True, verbose_name='Captured By'),
        ),
    ]
