# Generated by Django 5.2.5 on 2025-12-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_playerprofile_city_playerprofile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='picture',
            field=models.ImageField(blank=True, default='player_pics/default.jpg', null=True, upload_to='player_pics/%Y/%m/%d/'),
        ),
    ]
