# Generated by Django 5.2.5 on 2025-12-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_playerprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='hits',
            field=models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left'), ('S', 'Switch')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='school',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='throws',
            field=models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left'), ('S', 'Switch')], max_length=1, null=True),
        ),
    ]
